---
language: go
env:
  - GO111MODULE=on
go:
  - "1.12.x"

install:
  - echo $TRAVIS_GO_VERSION
script:
  - make
after_script:
  - bash <(curl -s https://codecov.io/bash)

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux